# Laravel Development Environment
name: CEG-HUB
services:
  # PHP Service (Laravel Application)
  php-fpm:
    build:
      context: ./docker/php
    container_name: php-fpm
    volumes:
      - ./src:/var/www/html
      - vendor_data:/var/www/html/vendor
    networks:
      - main-network
    restart: unless-stopped
    depends_on:
      - mongodb

  # Nginx Service
  nginx:
    build:
      context: ./docker/nginx
    container_name: nginx
    ports:
      - "8888:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - main-network
    restart: unless-stopped

  # MongoDB Service
  mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "9999:27017"
    volumes:
      - mongodb_data:/data/db
      - ./prod_data:/prod_data
      - ./docker/mongodb/init:/docker-entrypoint-initdb.d
    networks:
      - main-network
    restart: unless-stopped
    # 1. Start as a Replica Set named 'rs0'
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]

    # 2. Auto-initialize the Replica Set
    healthcheck:
      test: |
        mongosh --port 27017 --quiet --eval "
        try {
          rs.status().ok
        } catch (e) {
          rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'mongodb:27017'}]}).ok
        }"
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s


 # Node.js Service for Vite
  node:
    image: node:24-alpine
    container_name: node
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - node_modules:/var/www/html/node_modules
    ports:
      - "5173:5173"  # Vite dev server
    networks:
      - main-network
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000 # Check every 1000ms (1 second)
    #command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --debug"
    restart: unless-stopped

# Define networks
networks:
  main-network:
    driver: bridge

# Define volumes
volumes:
  mongodb_data:
    driver: local
  vendor_data:
    driver: local
  node_modules:
    driver: local