# Laravel Development Environment
name: CEG-HUB
services:
  # PHP Service (Laravel Application)
  php-fpm:
    build:
      context: ./docker/php
    container_name: php-fpm
    volumes:
      - ./src:/var/www/html
      - vendor_data:/var/www/html/vendor
    networks:
      - main-network
    restart: unless-stopped
    depends_on:
      - mongodb

  # Nginx Service
  nginx:
    build:
      context: ./docker/nginx
    container_name: nginx
    ports:
      - "8888:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - main-network
    restart: unless-stopped

  # MongoDB Service
  mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "9999:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: ceg_hub_database
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongodb/init:/docker-entrypoint-initdb.d
    networks:
      - main-network
    restart: unless-stopped


 # Node.js Service for Vite
  node:
    image: node:24-alpine
    container_name: node
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - node_modules:/var/www/html/node_modules
    ports:
      - "5173:5173"  # Vite dev server
    networks:
      - main-network
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    restart: unless-stopped

# Define networks
networks:
  main-network:
    driver: bridge

# Define volumes
volumes:
  mongodb_data:
    driver: local
  vendor_data:
    driver: local
  node_modules:
    driver: local